# Render configuration for the Next.js app
services:
  - type: web
    name: sparq-plug
    env: node
    plan: starter
    buildCommand: npm ci --no-audit --no-fund && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_BASE_PATH
        value: /app
      - key: UPLOAD_DIR
        value: /var/data/uploads
      - key: DATA_DIR
        value: /var/data/app-data
      # Uncomment and set your real keys
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: PUBLIC_URL
      #   value: https://sparq-plug.onrender.com
    healthCheckPath: /app/api/healthz
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
    disks:
      - name: app-data
        mountPath: /var/data
        sizeGB: 10
