services:
  # Webhook deployer: updates repos and rebuilds on GitHub push events
  deployer:
    build:
      context: ./deployer
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - REPO_OWNER=${REPO_OWNER:-hligon35}
      - MAIN_REPO=${MAIN_REPO:-sparq-plug}
      - PORTAL_REPO_NAME=${PORTAL_REPO_NAME:-sparq-dash}
      - STATIC_REPO_NAME=${STATIC_REPO_NAME:-sparq-landing}
      - ROOT_HOST=${ROOT_HOST:-getsparqd.com}
    volumes:
      - ..:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # This Next.js app (sparqplug.getsparqd.com)
  sparqplug:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        APP_BASE_PATH: ""
    environment:
      NODE_ENV: "production"
      APP_BASE_PATH: ""
      NEXT_PUBLIC_BASE_PATH: ""
      PUBLIC_URL: "https://sparqplug.getsparqd.com"
      UPLOAD_DIR: "/data/uploads"
      DATA_DIR: "/data/app-data"
      SSO_JWT_SECRET: "${SSO_JWT_SECRET:-change-me}"
    volumes:
      - sparqplug-data:/data
    restart: unless-stopped

  # Portal app (portal.getsparqd.com), built from external repo
  portal-app:
    build:
      context: ./portal-app/src
      dockerfile: ${PORTAL_DOCKERFILE:-Dockerfile}
    environment:
      NODE_ENV: production
      SSO_JWT_SECRET: "${SSO_JWT_SECRET:-change-me}"
    expose:
      - "3003"
    restart: unless-stopped

  # Static landing site (getsparqd.com) served by nginx
  static-site:
    image: nginx:1.27-alpine
    volumes:
      - ./static-site/build_out:/usr/share/nginx/html:ro
      - ./static-site/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  # Cloudflare Tunnel routing hostnames -> services
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared:rw
    user: "0:0"
    depends_on:
      - deployer
      - sparqplug
      - portal-app
      - static-site
    restart: unless-stopped

volumes:
  sparqplug-data: {}
